---
title: "Instructions for completing computer labs in the SCIE2204"
author: "Matt Navarro and Tim Langlois"
date: "26/03/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

We are running the computer practicals for SCIE2204 using R and you should all be able to complete this from either, using any web-based device (e.g. a tablet or laptop) at home or using a university computer. If you are having issues accessing a computer 


For each lab we will have an online video chat using Zoom during the scheduled lab times. 

The lab schedule is as follows:

- Lab 1 (Catch curve) Stream A: 31st March 9-11 
- Lab 1 (Catch curve) Stream B: 1st April 9-11
- Lab 1 (Catch curve) Stream C: 3rd April 14-16

- Lab 2 (Marine reserves) Stream A: 7th April 9-11
- Lab 2 (Marine reserves) Stream B: 8th April 9-11
- Lab 2 (Marine reserves) Stream C: 9th April 8-10 ******Note that this lab was rescheduled to avoid clash with Good Friday!!!

- Lab 3 (Oceanography) Stream c: 21st April 9-11
- Lab 3 (Oceanography) Stream B: 22nd April 9-11
- Lab 3 (Oceanography) Stream C: 24th April 14-16

You have two options for completing the labs:

1. You can log in to the video chat at **YOUR** scheduled lab time. **DO NOT SWAP LAB TIMES!!!** If you really need to switch email me: matthew.navarro@uwa.edu.au

OR

2. You can complete each lab in your own time **AFTER** 4pm. **BUT**, do not leave it all to the end, as you will miss the assessment deadlines! 

Why 4pm? We are running the labs by remotely accessing computers in the Eastern states (we are cloud computing), and we do not want to overload them. By 4pm everyone in the East has finished work leaving more room for us.

Even if you chose te complete the lab in your own time you can ask questions and get help by starting a thread in the LMS Discussion Board. Please post on the unit Discusion Board under ["Computer practicals"](https://lms.uwa.edu.au/webapps/discussionboard/do/forum?action=list_threads&course_id=_51767_1&nav=discussion_board_entry&conf_id=_214217_1&forum_id=_232476_1)



**Assessments** for the labs will consist of three short multi-choice quizzes, one for each lab. They should only take 5 minutes, so just complete them immediately after you have completed the lab! The quizzes will be on LMS. 

The quiz deadlines are as follows:

Lab 1 assessment: Due 12pm 9th April
Lab 2 assessment: Due 12pm 16th April
Lab 3 assessment: Due 12pm 30th April


## Instructions for video chat during scheduled lab time

### The video chat will use Zoom. 

To acccess the video chat click on the Zoom link corresponding to your class:

- Lab 1 Stream A: 31st March 9-11 <https://uwa.zoom.us/j/221032322>
- Lab 1 Stream B: 1 April 9-11 <https://uwa.zoom.us/j/639202405> 
- Lab 1 Stream C: 3 April 14-16 <https://uwa.zoom.us/j/280318223>


(**recommended**) Install Zoom before the lab. This will give you access to extra features. You can download Zoom from <https://zoom.us/download>

If you are using a Mac - please also complete these steps to allow Zoom acces to screen sharing.
<https://support.zoom.us/hc/en-us/articles/360016688031>


(**recommended**) Sign up for a UWA Zoom account which gives you access to even more features. Instructions for doing this are at <http://www.worldclasseducation.uwa.edu.au/__data/assets/pdf_file/0004/3446131/Zoom-Guide.pdf>


### Instructions for when in the Zoom meeting

We will potentially have 25 students logged in at once. To make things manageable we need to follow a few guidelines:

1. Unless you are speaking, please keep your **microphone muted** (click on the icon in the bottom left corner). You can have video on or off - it's up to you.

2. If you want to ask a question click on Participants in the centre and then click **raise hand**

3. When I respond to your Raised hand I will say your name. Unmute your microphone and ask your question. Note than you will be able to hear everyone elses questions and my responses. 

4. You can also use the **chat** to ask questions. I will try and keep an eye on it, but I may miss your question. If I do just raise your hand.

5. At some point I may ask you to share your screen . You can do this by clicking the share button in the bottom center of your Zoom window. 

Zoom works best when you have a reasonable internet connection. It will work on a mobile hostpot. 
If you do not have access to a reasonable internet connection, and you need help with the exercises, you maybe able access Unifi on campus.


## Instructions for how to complete the first lab

The first step is to start ecolcoud on your computer. Instructions on How-to-use-ecocloud - <https://github.com/UWA-SCIE2204-Marine-Systems/How-to-use-ecoloud>

The second step is to complete the exercises on the lab sheet - <https://github.com/UWA-SCIE2204-Marine-Systems/Catch-curve/blob/master/CatchCurveMarkdown.md>

Over the coming weeks you will be sent links to instructions on the second and third labs which are on marine reserves and oceanography respectively. 









