---
title: "Instructions for completing computer labs in the SCIE2204"
author: "Matt Navarro and Tim Langlois"
date: "26/03/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

We are running the three computer labs virtually for SCIE2204.

Your main instructor will be Matt Navarro <matthew.navarro@uwa.edu.au> with assitance from Tim Langlois.

We will be using R via the [ecocloud.org.au](https://app.ecocloud.org.au/) RStudio service, in the cloud.

You should all be able to complete these practicals with an internet connection from either home, using any web-based device (e.g. a tablet or laptop), or university using any available computer. If you are having issues accessing a computer please contact Matt via the unit Discusion Board under ["Computer practicals"](https://lms.uwa.edu.au/webapps/discussionboard/do/forum?action=list_threads&course_id=_51767_1&nav=discussion_board_entry&conf_id=_214217_1&forum_id=_232476_1)

Tim thinks you should be able to complete this entire practical on your smart phone - but we recommend a tablet with a keyboard  or computer if you can access one.

To provide assistance and answer any questions during each lab - we will have an online video chat using Zoom during the scheduled lab times.

To install and learn how to use Zoom - go to [Zoom_instructions](https://github.com/UWA-SCIE2204-Marine-Systems/1-instructions/blob/master/2-zoom-instructions.md)


### The lab and Zoom schedule is as follows:

- Lab 1 (Catch curve) Stream A: 31st March 9-11 
- Lab 1 (Catch curve) Stream B: 1st April 9-11
- Lab 1 (Catch curve) Stream C: 3rd April 14-16

- Lab 2 (Marine reserves) Stream A: 7th April 9-11
- Lab 2 (Marine reserves) Stream B: 8th April 9-11
- Lab 2 (Marine reserves) Stream C: 9th April 8-10 ******Note that this lab was rescheduled to avoid clash with Good Friday!!!

- Lab 3 (Oceanography) Stream c: 21st April 9-11
- Lab 3 (Oceanography) Stream B: 22nd April 9-11
- Lab 3 (Oceanography) Stream C: 24th April 14-16


### You have two options for completing the labs:

1. You can log in to the video chat at **YOUR** scheduled lab time. **DO NOT SWAP LAB TIMES!!!** If you really need to switch email Matt: matthew.navarro@uwa.edu.au

OR

2. You can complete each lab in your own time **AFTER** 4pm. **BUT**, do not leave it all to the end, as you will miss the assessment deadlines! 

Why 4pm? We are running the labs by remotely accessing computers in the Eastern states (we are cloud computing), and we do not want to overload them. By 4pm everyone in the East has finished work leaving more room for us.

Even if you chose to complete the lab in your own time you can ask questions and get help by starting a thread in the LMS Discussion Board. Please post on the unit Discusion Board under ["Computer practicals"](https://lms.uwa.edu.au/webapps/discussionboard/do/forum?action=list_threads&course_id=_51767_1&nav=discussion_board_entry&conf_id=_214217_1&forum_id=_232476_1)


## Assessments

The assesment for each labs will consist of three short multi-choice quizzes, one for each lab. They should only take 5 minutes and you should complete them **immediately** after you have completed the lab! The quizzes will be on LMS. 

The quiz deadlines are as follows:

Lab 1 assessment: Due 12pm 9th April
Lab 2 assessment: Due 12pm 16th April
Lab 3 assessment: Due 12pm 30th April


## Instructions for how to complete the first lab

The first step is to start ecolcoud. Go to [How-to-use-ecocloud](https://github.com/UWA-SCIE2204-Marine-Systems/1-instructions/blob/master/3-how-to-use-ecocloud.md)


The first practical in on [Catch curve analysis](https://github.com/UWA-SCIE2204-Marine-Systems/Catch-curve/blob/master/CatchCurveMarkdown.md)


Over the coming weeks you will be sent links to instructions on the second and third labs which are on marine reserves and biological oceanography respectively. 



Go back to [instructions](https://github.com/UWA-SCIE2204-Marine-Systems/1-instructions/blob/master/README.md)





